/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main.reader;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.database.Connect;
import swing.UIController;
import utilities.JTableFunction;
import view.login.LoginFrame;

/**
 *
 * @author Admin
 */
public class BookBorrowPanel extends javax.swing.JPanel {

    private JTableFunction function;
    private DefaultTableModel model;
    private String queryLoadData = "select b.id, c.category_name, b.title, b.Author, b.published_year, b.price from loan l inner join loan_detail ld on l.id = ld.loan_id inner join book b on ld.book_id = b.id inner join category c on c.id = b.category_id where l.account_id = '" + view.login.LoginFrame.account_id + "' and ld.detail_status = 0";
    
    /**
     * Creates new form BookBorrowPanel
     */
    public BookBorrowPanel() {
        initComponents();
        UIController.setDefaultTableHeader(jTable_Book);
        function = new JTableFunction();
        model = (DefaultTableModel) jTable_Book.getModel();
        function.LoadData(jTable_Book, queryLoadData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_NgayMuon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_HanTra = new javax.swing.JLabel();
        jLabel_Phat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Book = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Ngày mượn:");

        jLabel_NgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Hạn trả:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Phạt:");

        jLabel_HanTra.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel_Phat.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Phat.setText("Đã trễ ... phải nộp phạt ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_NgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel_HanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Phat, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_NgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Phat)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_HanTra)
                    .addComponent(jLabel10))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTable_Book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", "Title", "Author", "Published year", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Book);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BookMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_Book.getSelectedRow();
        if(selectedRow == -1)
            return;
        
        String bookID = model.getValueAt(selectedRow, 0).toString();
        getBorrowInformation(view.login.LoginFrame.account_id, bookID);
    }//GEN-LAST:event_jTable_BookMouseClicked

    
    public void getBorrowInformation(String username, String bookID) {
        String query = "select l.date_start, ld.date_end, r.overdue_fine from loan l inner join loan_detail ld on ld.loan_id = l.id inner join loan_rule r on l.loan_rule_id = r.id where ld.book_id = ? and l.account_id = ?";
        int overDueFines = 0;
        String borrowDate = null;
        String expirationDate = null;
        int fines = 0;
        try {
            Connection con = Connect.GetConnect();
            PreparedStatement ps = con.prepareStatement(query);
			ps.setString(1, bookID);
			ps.setString(2, username);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                borrowDate = rs.getString(1);
                expirationDate = rs.getString(2);
                overDueFines = rs.getInt(3);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        // Calculate days between today and hanTra
        LocalDate today = LocalDate.now();
        LocalDate hanTra = LocalDate.parse(expirationDate);
        Duration diff = Duration.between(hanTra.atStartOfDay(), today.atStartOfDay());
        long diffDays = diff.toDays();
        System.out.println("Số ngày trễ hạn: " + diffDays);
        
        // Check if the book is returned late or not
        if (diffDays > 0)
            fines = (int) (overDueFines * diffDays);
        
        jLabel_NgayMuon.setText(borrowDate);
        jLabel_HanTra.setText(expirationDate);
        jLabel_Phat.setText("Đã trễ " + (diffDays < 0 ? 0 : diffDays) + " ngày phải nộp phạt " + fines + " đồng");        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_HanTra;
    private javax.swing.JLabel jLabel_NgayMuon;
    private javax.swing.JLabel jLabel_Phat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Book;
    // End of variables declaration//GEN-END:variables
}
